apiVersion: v1
kind: Pod
metadata:
  name: ds-curso-video
  labels:
    app: ds-curso-video
spec:
  containers:
    - name: ds-curso-video-container
      image: davisouza23/ds_curso_video_image:latest
      ports:
        - containerPort: 8000
      envFrom:
        - configMapRef:
            name: ds-curso-video-configmap