apiVersion: v1
kind: Service
metadata:
  name: svc-ds-curso-video
spec:
  type: TCP #NodePort
  ports:
    - port: 8000
      targetPort: 8000
      #nodePort: 30000
  selector:
    app: ds-curso-video